name: CI

on: [push]

jobs:
  validate:
    runs-on: [self-hosted, windows, X64]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
  lint:
    runs-on: [self-hosted, windows, X64]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives
  build:
    name: build
    runs-on: [self-hosted, windows, X64]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build with HEMTT
      id: build
      run: |
        ./hemtt build