name: 'RELEASE'

on:
  release:
    types: [published]

jobs:
  upload-to-steam:
    name: Upload to Steam Workshop
    if: ${{ !github.event.release.prerelease }} # Do not upload pre releases
    runs-on: windows-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Build with HEMTT
          uses: gruppe-adler/action-release-with-hemtt@2.2.0
          id: build
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: ${{ steps.build.outputs.zip_name }}
            path: ${{ steps.build.outputs.zip_path }}