name: 'RELEASE'

on:
  release:
    types: [published]

jobs:
  create-artifact:
    name: Create Artifact
    if: ${{ !github.event.release.prerelease }} # Do not upload pre releases
    runs-on: windows-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Build with HEMTT
          uses: gruppe-adler/action-release-with-hemtt@2.2.0
          id: build
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: ${{ steps.build.outputs.zip_name }}
            path: ${{ steps.build.outputs.zip_path }}
        - name: Add artifact to assets
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ${{ steps.build.outputs.zip_path }}
            asset_name: ${{ steps.build.outputs.zip_name }}
            asset_content_type: application/zip